# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#

kanto  = Generation.create({ name: 'Kanto' })
johto  = Generation.create({ name: 'Johto' })
hoenn  = Generation.create({ name: 'Hoenn' })
sinnoh  = Generation.create({ name: 'Sinnoh' })
unova  = Generation.create({ name: 'Unova' })
kalos  = Generation.create({ name: 'Kalos' })
alola  = Generation.create({ name: 'Alola' })
galar  = Generation.create({ name: 'Galar' })

normal = Type.create({ name: 'Normal', icon: 'https://static.wikia.nocookie.net/pokemongo/images/4/43/Icon_Normal.png' })
fighting = Type.create({ name: 'Fighting', icon: 'https://static.wikia.nocookie.net/pokemongo/images/f/f0/Icon_Fighting.png' })
flying = Type.create({ name: 'Flying', icon: 'https://static.wikia.nocookie.net/pokemongo/images/b/b0/Icon_Flying.png' })
poison = Type.create({ name: 'Poison', icon: 'https://static.wikia.nocookie.net/pokemongo/images/2/26/Icon_Poison.png' })
ground = Type.create({ name: 'Ground', icon: 'https://static.wikia.nocookie.net/pokemongo/images/7/71/Icon_Ground.png' })
rock = Type.create({ name: 'Rock', icon: 'https://static.wikia.nocookie.net/pokemongo/images/5/57/Icon_Rock.png' })
bug = Type.create({ name: 'Bug', icon: 'https://static.wikia.nocookie.net/pokemongo/images/8/88/Icon_Bug.png' })
ghost = Type.create({ name: 'Ghost', icon: 'https://static.wikia.nocookie.net/pokemongo/images/7/7d/Icon_Ghost.png' })
fire = Type.create({ name: 'Fire', icon: 'https://static.wikia.nocookie.net/pokemongo/images/0/0a/Icon_Fire.png' })
water = Type.create({ name: 'Water', icon: 'https://static.wikia.nocookie.net/pokemongo/images/6/65/Icon_Water.png' })
grass = Type.create({ name: 'Grass', icon: 'https://static.wikia.nocookie.net/pokemongo/images/0/0a/Icon_Grass.png' })
electric = Type.create({ name: 'Electric', icon: 'https://static.wikia.nocookie.net/pokemongo/images/1/1c/Icon_Electric.png' })
psychic = Type.create({ name: 'Psychic', icon: 'https://static.wikia.nocookie.net/pokemongo/images/c/ce/Icon_Psychic.png' })
ice = Type.create({ name: 'Ice', icon: 'https://static.wikia.nocookie.net/pokemongo/images/5/52/Icon_Ice.png' })
dragon = Type.create({ name: 'Dragon', icon: 'https://static.wikia.nocookie.net/pokemongo/images/d/d4/Icon_Dragon.png' })
dark = Type.create({ name: 'Dark', icon: 'https://static.wikia.nocookie.net/pokemongo/images/e/e9/Icon_Dark.png' })
steel = Type.create({ name: 'Steel', icon: 'https://static.wikia.nocookie.net/pokemongo/images/3/38/Icon_Steel.png' })
fairy = Type.create({ name: 'Fairy', icon: 'https://static.wikia.nocookie.net/pokemongo/images/7/7f/Icon_Fairy.png' })